#
#

development:
  adapter: postgresql
  encoding: utf8
  database: gear_closet_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gear_closet_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: gear_closet_production
  pool: 5
  username: 
  password: