# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecaf2e44b02a5a0fa368bcaa38779c227d2a3dced8a7f791d05faa36a0a7010edafa594d6395f0ebbf60b5b0e2dcf72011c7d695ff0d0a96d6e26661c5ef7d19

test:
  secret_key_base: 0d005384d3f06f87530525883c832b78bd10e3566c26a6b6cd141e509bd2b15de3cf35dfb14ee7b81f49aa042e69eb674d8ec639419dc3d1902c4f74d6251162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
